query getPokemonList(
  $limit: Int
  $order_by: [pokemon_v2_pokemon_order_by!]
  $where: pokemon_v2_pokemon_bool_exp
) {
  pokemon_v2_pokemon(limit: $limit, order_by: $order_by, where: $where) {
    id
    name
    pokemon_v2_pokemonsprites {
      sprites
    }
    pokemon_v2_pokemonstats {
      base_stat
    }
  }
}
